### ISSUE TITLE
numpy RuntimeWarnings when specifing infinite bounds

### ISSUE THREAD

**Issue by roecla** [fides-dev/fides#46] opened 2021-11-23 10:50 UTC
###  Problem Description
In the docstring for the `Optimizer` class, you write that parameters without bounds should get `-inf` / `inf`. 

When I do this, I get a lot of RuntimeWarnings in [minimize.py:640](https://github.com/fides-dev/fides/blob/db158b4e872e3797f7d6b1510805d5d13fb5949d/fides/minimize.py#L640).

### Analysis

The relevant lines are [634](https://github.com/fides-dev/fides/blob/db158b4e872e3797f7d6b1510805d5d13fb5949d/fides/minimize.py#L634) and [640](https://github.com/fides-dev/fides/blob/db158b4e872e3797f7d6b1510805d5d13fb5949d/fides/minimize.py#L640):

```python
        v = np.sign(self.grad) + (self.grad == 0)
        bounds = ((1 + v)*self.lb + (1 - v)*self.ub)/2
```

The `RuntimeWarning` stems not from the infinite values but from a `np.nan` that appears when multiplying `0*np.inf`. 
Here is an minimal example to see this: 

```python
import numpy as np

ub = np.array([3, 3, 3, np.inf])
lb = np.array([-np.inf, 0, 0, 0])

grad = np.array([-3, 0, 3, -3])
# v: -1 where grad < 0, 1 where grad >= 0
v = np.sign(grad) + (grad == 0)

# (1 + v) / 2 = [0, 1, 1, 0], (1 - v) / 2 = [1, 0, 0, 1]
summand1 = (1 + v) / 2 * lb  # 0 * -np.inf causes the runtime warning
summand2 = (1 - v) / 2 * ub

bounds = summand1 + summand2
bounds
```

If I understand your code right, you are implementing an if condition: Choose the lower bounds when the gradient is weakly positive and the upper bound otherwise. 

However, there is one exception to this: when the **not** chosen bound is +/- `inf`. In that case your bounds are NaN which is what causes the `RuntimeWarning`.

### Solution Proposal

If that NaN is not wanted, a one line solution that avoids the `RuntimeWarning` is `np.where(grad<0, ub, lb)`. If that NaN is important you can still get the same behavior in three lines without triggering the Warning:

```python
bounds2 = np.where(grad<0, ub, lb)
# you need the np.logical_and here because the arrays are numpy bools
bounds2[np.logical_and(grad<0, ~np.isfinite(lb))] = np.nan
bounds2[np.logical_and(grad>=0, ~np.isfinite(ub))] = np.nan

```

### Specification

I am using the latest `numpy`: 1.21.4 and the latest Fides: 0.7.1

**Comment by FFroehlich** [comment] 2021-11-23 16:46
Thanks for reporting this and proposing a solution!

You are indeed correct that this will result in `np.nan` values in the `bounded` variable and numpy throwing a runtime warning. However, `np.isfinite` checks for both `np.inf` and `np.nan` values, so the code is nevertheless working as intended. 

I see how the runtime warning may be confusing users, so this will be fixed in an upcoming release.

**Closed** 2021-11-26 01:49 UTC
